name: Test Workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test
  upload:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: Install packages
        run: npm ci
      - name: run build
        run: npm run build
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist
  deploy:
    needs: upload
    runs-on: ubuntu-latest
    steps:
      - name: download build
        uses: actions/download-artifact@v4
        with:
          name: dist-files
      - name: run ls
        run: ls
      - name: deploy
        run: echo "deploying..."
